sonar.projectKey=PI_T1_Docs
sonar.projectName=PI_T1 Documentation Wiki
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.astro/**
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.e1.resourceKey=**/custom.css
